[tools]
age = "latest"
ant = "1.10.15"
buf = "latest"
bun = "latest"
chezmoi = "latest"
go = "1.24.9"
gradle = "latest"
helm = "latest"
java = "temurin-21.0.9+10.0.LTS"
lua = "5.1"
node = "22.9.0"
protoc = "latest"
python = "3.13.5"
sops = "latest"
uv = "latest"
